# Generated by Django 5.2.3 on 2025-06-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_index', models.IntegerField(default=0)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.label')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sentence')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('text', 'label'), name='unique_pos_text_label')],
            },
        ),
    ]
