# Generated by Django 5.1.6 on 2025-02-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
