# Generated by Django 5.2.3 on 2025-06-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_poslabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='religion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.religion'),
        ),
    ]
