# Generated by Django 5.1.6 on 2025-02-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='denomination',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
