# Generated by Django 5.1.6 on 2025-03-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_book_id_book_description_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
