# Generated by Django 5.1.6 on 2025-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
