# Generated by Django 5.2.3 on 2025-06-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_word_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='type',
            field=models.CharField(default='NER', max_length=50),
        ),
    ]
