# Generated by Django 5.2.3 on 2025-06-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_label_type_alter_religion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='religion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.religion'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
