# Generated by Django 5.2.3 on 2025-06-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_book_religion_alter_religion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
