# Generated by Django 5.2.3 on 2025-06-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_label_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.TextField(default='yellow'),
        ),
        migrations.AddField(
            model_name='note',
            name='sentence_index_end',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='sentence_index_start',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='word_index_end',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='word_index_start',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.tag'),
        ),
    ]
