# Generated by Django 5.1.6 on 2025-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bookformat_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookformat',
            name='columns',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
        ),
    ]
