# Generated by Django 5.2.3 on 2025-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tag_note_color_note_sentence_index_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='chapter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='page',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
