# Generated by Django 5.2.3 on 2025-07-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_note_chapter_note_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='sentence',
            name='chapter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='api.chapter'),
        ),
    ]
