# Generated by Django 5.2.3 on 2025-07-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chapter_alter_sentence_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='api.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookformat',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
