# Generated by Django 5.2.3 on 2025-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chapter_book_alter_bookformat_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='current_chapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='current_word',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='current_page',
            field=models.IntegerField(default=0),
        ),
    ]
