# Generated by Django 5.2.3 on 2025-07-08 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_bookmark_current_chapter_bookmark_current_word_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_bookmark'),
        ),
    ]
