# Generated by Django 5.2.3 on 2025-07-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bookmark_unique_user_book_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
